### ISSUE TITLE
Babolat POP armband sensor json export

### ISSUE THREAD

**Issue by overdrivek** [diox/la-playa#3]
Hi there, 
I am quite interested if the babolat pop armband sensor data can also be exported to a json file for custom graph creation? I have been trying to find if the sensor has a SDK, till now to no avail. It would be great if you have some ideas where I could focus.. 
Thanks

**Comment by diox** [comment]
Hey,

Sorry, I have no idea. As you can see from the lack to updates to the repos I haven't played in a while and haven't done any research in this space. We used to [import the data directly from babolat's website](https://github.com/diox/la-playa/blob/gh-pages/import_json.py), maybe they have something similar for the armband, I haven't checked.
